"""Add dummy column to Comment model

Revision ID: b2e9b003161b
Revises: afb3642c5c2d
Create Date: 2024-10-07 00:22:50.883046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e9b003161b'
down_revision = 'afb3642c5c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###
