"""Remove dummy column from Comment model

Revision ID: e6a3b6871737
Revises: b2e9b003161b
Create Date: 2024-10-07 00:23:33.590289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a3b6871737'
down_revision = 'b2e9b003161b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
